// NOTE: this file is auto-generated by Construct
declare class IConstructProjectObjects {
	readonly player: IObjectType<InstanceType.player>;
	readonly ground: IObjectType<InstanceType.ground>;
	readonly Keyboard: IKeyboardObjectType<InstanceType.Keyboard>;
	readonly hostIndicator: IObjectType<InstanceType.hostIndicator>;
	readonly Multiplayer: IMultiplayerObjectType<InstanceType.Multiplayer>;
	readonly txtDebug: IObjectType<InstanceType.txtDebug>;
	readonly lblName: IObjectType<InstanceType.lblName>;
}